Neos:
  Flow:
    http:
      middlewares:
        'addCacheHeader':
          middleware: 'Flowpack\Varnish\Middleware\CacheControlHeaderComponent'
          position: 'after securityEntryPoint'

  Neos:
    modules:
      administration:
        submodules:
          varnish:
            label: 'Varnish cache purging'
            controller: \Flowpack\Varnish\Controller\VarnishCacheController
            description: 'Clear Varnish cache.'
            icon: 'fa fa-bolt'
            additionalResources:
              javaScripts:
                - 'resource://Flowpack.Varnish/Public/Libraries/jquery/jquery-3.6.0.min.js'
              styleSheets:
                - 'resource://Flowpack.Varnish/Public/Styles/Module.css'
            privilegeTarget: 'Flowpack.Varnish:BackendModuleClearCache'
    fusion:
      autoInclude:
        Flowpack.Varnish: true
