Neos:
  Flow:
    http:
      chain:
        'process':
          chain:
            addCacheHeader:
              position: 'after setHeader'
              component: 'Flowpack\Varnish\Http\CacheControlHeaderComponent'

  Neos:
    modules:
      administration:
        submodules:
          varnish:
            label: 'Varnish cache purging'
            controller: \Flowpack\Varnish\Controller\VarnishCacheController
            description: 'Clear Varnish cache.'
            icon: 'fa fa-bolt'
            additionalResources:
              styleSheets:
                - 'resource://Flowpack.Varnish/Public/Styles/Module.css'
            privilegeTarget: 'Flowpack.Varnish:BackendModuleClearCache'
    fusion:
      autoInclude:
        Flowpack.Varnish: true
